### ISSUE TITLE
Chat doesnt work on Firefox 35?

### ISSUE THREAD

**Issue by ChikNoods** [destinygg/chat#23]
Nothing in chat works on firefox 35.0.1. It just a blank screen. Video will load, but you cant press any buttons in chat and nothing is scrolling. You can hover buttons and they will turn white, but nothing pops up. Works in other browsers just fine.

**Comment by cene-co-za** [comment]
Could you provide a screen shot?

From your description I cannot tell if the whole chat simply does "nothing"
or you are at least getting the connection error messages.

I have checked in Firefox 35.0.1 - and the chat functions correctly.
Closing until more info given.

**Comment by ChikNoods** [comment]
it doesnt do anything. http://i.imgur.com/QIZKUWu.jpg

regular twitch works fine. Works in firefox 27 on my laptop. Doesn't do shit on 35 on desktop

**Comment by ChikNoods** [comment]
http://www.destiny.gg/embed/chat that doesnt do anything either. Its just blank. I disabled anything that would affect it and its still blank. I dont want to use Internet explorer DaFeels

**Comment by cene-co-za** [comment]
on http://www.destiny.gg/embed/chat -- press `cntrl` + `shift` + `k`
and send me a screenshot of the errors.

**Comment by ChikNoods** [comment]
http://i.imgur.com/xNNV60b.jpg

**Comment by sztanpet** [comment]
try https://www.destiny.gg/embed/chat
i have a feeling that something is modifying the javascript on your side

**Comment by ChikNoods** [comment]
https://www.destiny.gg/embed/chat works. is it the https? Weird that i would have something new modify the https. I directly copied my firefox27 profile over to my firefox35, so any modifications would still be in there. I guess ill try to find out

**Comment by sztanpet** [comment]
yes, the https means that the connection is encrypted so things have to make an effort to hijack the connection

which is happening by default for you on pure http, so beware

**Comment by ChikNoods** [comment]
This is a new OS install. The only thing different from the laptop and the desktop is, im trying out AVAST on the new desktop. AVG is on the desktop. If it really were an http/https issue than regular twitch wouldnt work either right? in http? I know the addon HTTPS everywhere had some twitch issues a few months ago. I'l double check everything, but atleast we know its https related and i've since updated my bookmark to HTTPS, which it should have been in the first place. Thanks for the reply

**Comment by sztanpet** [comment]
no, things can still work, you just noticed this break destinygg, it wont necessarily break twitch

also, destiny.gg/bigscreen wont work in https yet, so only use https with the chat (destiny.gg/embed/chat)
