### ISSUE TITLE
Jump to chat with keyboard combination

### ISSUE THREAD

**Issue by bliutwo** [destinygg/chat#26]
When you click on the twitch player for any reason (volume, quality change, etc.) your cursor is no longer in chat to type. Ideally, there would be a keyboard/button combination that lets you jump straight to the chat line so that you can continue typing in chat, similar to Ctrl+L or Command+L in your browser.

**Comment by bliutwo** [comment]
Correction: according to Vaan99, this issue happens EVERY time as opposed to sometimes.

**Comment by cene-co-za** [comment]
Although I doubt we'd implement something like this. 
If you wish to log your feature request, do so in the [destinygg/website](https://github.com/destinygg/website) repo. 
This is a front-end feature.
