### ISSUE TITLE
@ pop up a window of matching users

### ISSUE THREAD

**Issue by Pheelbert** [destinygg/chat#28]
![image](https://cloud.githubusercontent.com/assets/5648665/24075870/19e80762-0bfa-11e7-8197-a31c8a5d6f13.png)

PS: Not sure where to put suggestions

**Comment by cene-co-za** [comment]
Could you please raise this issue in the destinygg/website repository.
This repository is for back-end only.

**Comment by sztanpet** [comment]
or just dont even bother, not going to happen
