### ISSUE TITLE
Ability to add highlighting with no authentication

### ISSUE THREAD

**Issue by harknesslabs** [destinygg/chat#39]
Would appreciate the ability to do a https://www.destiny.gg/embed/chat?highlight=dan without being signed into the chat.

OBS allows me to add a custom dock url and I use this to embed dgg chat. However, It does not enable highlighting on my name.

To clarify, loading https://www.destiny.gg/embed/chat?highlight=dan would simply enable highlighting for that term, even if not logged in.

Stupid feature I know and certainly nor priority, but if its easy to do I would appreciate it.

**Comment by ILiedAboutCake** [comment]
this should be in https://github.com/destinygg/chat-gui, this repo is for the chatserver.

I don't think this would be something we would add.
