### ISSUE TITLE
window resizes too far in chat-left view while chat is bottom-docked

### ISSUE THREAD

**Issue by picklesnathan** [destinygg/chat#44]
# I'm getting really bothered by something really small and trying to learn some coding at the same time. 
thank you for your patience

## Description
The way I position my broswer windows causes the #chat-panel element to place its #chat-panel-resize-bar juuuuust offscreen. This then forces my browser to draw a horizontal scrollbar and I find that simply unacceptable and visually distracting. From what I can tell the placement and width of the resize bar (only while the #chat-panel element is of class 'chat-left') ends up just outside the max-width of the page since its placed all the way to the right and then draws itself outwards(?). 

All and all this is not a big deal but its bothering me enough to mention it.

## How to reproduce:
- works in chrome, firefox, edge, and firefox mobile browser emulator
- go to dgg bigscreen view
- zoom the page in or resize the window until the chat snaps to the bottom
- press the 'Swap' chat toolbar button so that the #chat-panel is in its #chat-left state
- this should procue a horizontal scrollbar that needs to be scrolled to the right in order to touch the resize-bar.

## Solutions
- resize the window until the chat pops back into the left/right spit.
- if you're in the top/down split view, just press the 'Swap' button
- I wrote a userscript that removes the entire element. This was truly unneccessary but it was kinda fun to investigate. 
![image](https://user-images.githubusercontent.com/103597670/170394625-d49c36c8-1d64-433b-96a9-e5463dffd7ec.png)

**Comment by ILiedAboutCake** [comment]
Issue should be opened in https://github.com/destinygg/chat-gui. This repo is for the deprecated backend chat server.
